/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import domain.Iznajmljivanje;
import domain.StavkaIznajmljivanja;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import kontroler.Komunikacija;
import modeli.ModelTabeleStavkaIznajmljivanja;
import transfer.Request;
import transfer.Response;
import transfer.util.Operacije;

/**
 *
 * @author mihajlodjordjevic
 */
public class DetaljiIznajmljivanjaForm extends javax.swing.JFrame {

    private Iznajmljivanje iznajmljivanje;

    /**
     * Creates new form DetaljiIznajmljivanjaForm
     */
    public DetaljiIznajmljivanjaForm(Iznajmljivanje iz) {
        initComponents();
        setTitle("Detalji iznajmljivanja");
        setLocationRelativeTo(null);
        this.iznajmljivanje = iz;
        popuniTabelu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblStavke = new javax.swing.JTable();
        btnIzmeniStavkuIznajmljivanja = new javax.swing.JButton();
        btnZatvori = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblStavke.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblStavke);

        btnIzmeniStavkuIznajmljivanja.setText("Izmeni stavku iznajmljivanja");
        btnIzmeniStavkuIznajmljivanja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniStavkuIznajmljivanjaActionPerformed(evt);
            }
        });

        btnZatvori.setText("Zatvori");
        btnZatvori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZatvoriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnIzmeniStavkuIznajmljivanja, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnZatvori, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIzmeniStavkuIznajmljivanja)
                    .addComponent(btnZatvori))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnZatvoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZatvoriActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnZatvoriActionPerformed

    private void btnIzmeniStavkuIznajmljivanjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniStavkuIznajmljivanjaActionPerformed
        int selectedRow = tblStavke.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Morate odabrati neku stavku!", "Greska!", JOptionPane.ERROR_MESSAGE);
            return;
        }

        ModelTabeleStavkaIznajmljivanja model = (ModelTabeleStavkaIznajmljivanja) tblStavke.getModel();
        StavkaIznajmljivanja si = model.getStavkaAt(selectedRow);

        IzmeniStavkuIznajmljivanjaForm isif = new IzmeniStavkuIznajmljivanjaForm(this, true, si);
        isif.setVisible(true);
    }//GEN-LAST:event_btnIzmeniStavkuIznajmljivanjaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeniStavkuIznajmljivanja;
    private javax.swing.JButton btnZatvori;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblStavke;
    // End of variables declaration//GEN-END:variables

    private void popuniTabelu() {
        try {
            StavkaIznajmljivanja kriterijum = new StavkaIznajmljivanja();
            kriterijum.setIznajmljivanje(iznajmljivanje);

            Request zahtev = new Request();
            zahtev.setData(kriterijum);
            zahtev.setOperation(Operacije.GET_ALL_STAVKA_IZNAJMLJIVANJA);

            Komunikacija.getInstance().posaljiZahtev(zahtev);
            Response odgovor = Komunikacija.getInstance().primiOdgovor();

            ArrayList<StavkaIznajmljivanja> stavke = (ArrayList<StavkaIznajmljivanja>) odgovor.getResult();
            tblStavke.setModel(new ModelTabeleStavkaIznajmljivanja(stavke));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Greska prilikom ucitavanja stavki iznajmljivanja!", "Greska!", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    
    public void osveziTabelu() {
    try {
        StavkaIznajmljivanja kriterijum = new StavkaIznajmljivanja();
        kriterijum.setIznajmljivanje(iznajmljivanje);

        Request zahtev = new Request();
        zahtev.setData(kriterijum);
        zahtev.setOperation(Operacije.GET_ALL_STAVKA_IZNAJMLJIVANJA);

        Komunikacija.getInstance().posaljiZahtev(zahtev);
        Response odgovor = Komunikacija.getInstance().primiOdgovor();

        ArrayList<StavkaIznajmljivanja> stavke = (ArrayList<StavkaIznajmljivanja>) odgovor.getResult();
        tblStavke.setModel(new ModelTabeleStavkaIznajmljivanja(stavke));
    } catch (Exception ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Greska prilikom osvežavanja tabele!", "Greska!", JOptionPane.ERROR_MESSAGE);
    }
}

}
