/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forme;

import domain.Automobil;
import domain.Iznajmljivanje;
import domain.Klijent;
import domain.ParametarDostupnihAutomobila;
import domain.Radnik;
import domain.StavkaIznajmljivanja;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import kontroler.Komunikacija;
import modeli.ModelTabeleStavkaIznajmljivanja;
import transfer.Request;
import transfer.Response;
import transfer.util.Operacije;

/**
 *
 * @author mihajlodjordjevic
 */
public class DodajiznajmljivanjeForm extends javax.swing.JDialog {

    private ModelTabeleStavkaIznajmljivanja mt;
    private Klijent zakljucaniKlijent = null;

    /**
     * Creates new form DodajiznajmljivanjeForm
     */
    public DodajiznajmljivanjeForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        DocumentListener listener = new DocumentListener() {
            public void insertUpdate(DocumentEvent e) {
                popuniDostupneAutomobile();
            }

            public void removeUpdate(DocumentEvent e) {
                popuniDostupneAutomobile();
            }

            public void changedUpdate(DocumentEvent e) {
                popuniDostupneAutomobile();
            }
        };
        txtDatumOd.getDocument().addDocumentListener(listener);
        txtDatumDo.getDocument().addDocumentListener(listener);
        setLocationRelativeTo(null);
        popuniKlijente();
        popuniAutomobile();
        mt = new ModelTabeleStavkaIznajmljivanja();
        tblStavkaIznajmljivanja.setModel(mt);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbKlijent = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        cmbAutomobil = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        txtDatumOd = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDatumDo = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStavkaIznajmljivanja = new javax.swing.JTable();
        btnDodajStavku = new javax.swing.JButton();
        btnSacuvajIznajmljivanje = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtNapomena = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        btnOtkazi = new javax.swing.JButton();
        btnObrisiStavku = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtOpis = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Klijent:");

        cmbKlijent.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Automobil:");

        cmbAutomobil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbAutomobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAutomobilActionPerformed(evt);
            }
        });

        jLabel3.setText("Datum Od:");

        txtDatumOd.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd.MM.yyyy"))));

        jLabel4.setText("Datum Do:");

        txtDatumDo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd.MM.yyyy"))));

        tblStavkaIznajmljivanja.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblStavkaIznajmljivanja);

        btnDodajStavku.setText("Dodaj Stavku Iznajmljivanja");
        btnDodajStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajStavkuActionPerformed(evt);
            }
        });

        btnSacuvajIznajmljivanje.setText("Sacuvaj Iznajmljivanje");
        btnSacuvajIznajmljivanje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajIznajmljivanjeActionPerformed(evt);
            }
        });

        txtNapomena.setColumns(20);
        txtNapomena.setRows(5);
        jScrollPane2.setViewportView(txtNapomena);

        jLabel5.setText("Napomena:");

        btnOtkazi.setText("Otkazi");
        btnOtkazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOtkaziActionPerformed(evt);
            }
        });

        btnObrisiStavku.setText("Obrisi Stavku Iznajmljivanja");
        btnObrisiStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiStavkuActionPerformed(evt);
            }
        });

        txtOpis.setColumns(20);
        txtOpis.setRows(5);
        jScrollPane3.setViewportView(txtOpis);

        jLabel6.setText("Opis:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSacuvajIznajmljivanje)
                        .addGap(49, 49, 49)
                        .addComponent(btnOtkazi))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cmbKlijent, 0, 525, Short.MAX_VALUE)
                                .addComponent(cmbAutomobil, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtDatumOd))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnDodajStavku)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnObrisiStavku))
                                .addComponent(txtDatumDo)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(30, 30, 30)
                            .addComponent(jScrollPane3))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cmbKlijent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(cmbAutomobil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(txtDatumOd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDatumDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDodajStavku, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnObrisiStavku, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSacuvajIznajmljivanje)
                    .addComponent(btnOtkazi))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbAutomobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAutomobilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbAutomobilActionPerformed

    private void btnOtkaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOtkaziActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnOtkaziActionPerformed

    private void btnDodajStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajStavkuActionPerformed

        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
        try {
            Klijent klijent = (Klijent) cmbKlijent.getSelectedItem();
            if (zakljucaniKlijent == null) {
                zakljucaniKlijent = klijent;
                cmbKlijent.setEnabled(false);
            } else {
                if (!zakljucaniKlijent.equals(klijent)) {
                    JOptionPane.showMessageDialog(this, "Sve stavke moraju biti za istog klijenta!", "Greška!", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
            Automobil automobil = (Automobil) cmbAutomobil.getSelectedItem();
            String datumOdText = txtDatumOd.getText();
            String datumDoText = txtDatumDo.getText();
            String napomena = txtNapomena.getText();

            if (klijent == null || automobil == null || datumOdText.isEmpty() || datumDoText.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Sva polja moraju biti popunjena!", "Greska!", JOptionPane.ERROR_MESSAGE);
                return;
            }

            Date datumOd = sdf.parse(datumOdText);
            Date datumDo = sdf.parse(datumDoText);

            if (datumOd.after(datumDo)) {
                JOptionPane.showMessageDialog(this, "Datum OD mora biti pre datuma DO!", "Greška!", JOptionPane.ERROR_MESSAGE);
                return;
            }

            int brojDana = (int) (datumDo.getTime() - datumOd.getTime()) / (1000 * 60 * 60 * 24);
            if (brojDana == 0) {
                brojDana = 1;
            }
            double cena = brojDana * automobil.getCenaPoDanu();
            int rb = mt.getRowCount() + 1;
            for (int i = 0; i < mt.getRowCount(); i++) {
                StavkaIznajmljivanja si = mt.getStavkaAt(i);
                Automobil a = si.getAutomobi();

                if (a.getAutomobilID() == automobil.getAutomobilID()
                        && datumiSePreklapaju(si.getDatumOd(), si.getDatumDo(), datumOd, datumDo)) {
                    JOptionPane.showMessageDialog(this, "Automobil je već dodat za izabrani termin.");
                    return;
                }
            }
            StavkaIznajmljivanja stavkaIznajmljivanja = new StavkaIznajmljivanja(null, rb, napomena, datumOd, datumDo, brojDana, cena, automobil);
            mt.dodajStavku(stavkaIznajmljivanja);

            txtDatumDo.setText("");
            txtDatumOd.setText("");
            txtNapomena.setText("");
        } catch (ParseException ex) {
            Logger.getLogger(DodajiznajmljivanjeForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDodajStavkuActionPerformed

    private void btnObrisiStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiStavkuActionPerformed
        int selectedRow = tblStavkaIznajmljivanja.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Morate izabrati stavku za brisanje!", "Greška!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        ModelTabeleStavkaIznajmljivanja mt = (ModelTabeleStavkaIznajmljivanja) tblStavkaIznajmljivanja.getModel();
        mt.getLista().remove(selectedRow);

        for (int i = 0; i < mt.getLista().size(); i++) {
            mt.getLista().get(i).setRb(i + 1);
        }
        mt.fireTableDataChanged();

        if (mt.getLista().isEmpty()) {
            zakljucaniKlijent = null;
            cmbKlijent.setEnabled(true);
        }
    }//GEN-LAST:event_btnObrisiStavkuActionPerformed

    private void btnSacuvajIznajmljivanjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajIznajmljivanjeActionPerformed
        try {
            String opis = txtOpis.getText();
            double ukupanIznos = 0;

            ModelTabeleStavkaIznajmljivanja mt = (ModelTabeleStavkaIznajmljivanja) tblStavkaIznajmljivanja.getModel();
            ArrayList<StavkaIznajmljivanja> lista = mt.getLista();

            for (StavkaIznajmljivanja stavkaIznajmljivanja : lista) {
                ukupanIznos += stavkaIznajmljivanja.getCena();
            }

            Klijent k = (Klijent) cmbKlijent.getSelectedItem();
            Radnik r = Komunikacija.getInstance().getZaposleni();

            //  Dodaj direktno stavke prilikom pravljenja objekta
            Iznajmljivanje iz = new Iznajmljivanje(-1, new Date(), opis, ukupanIznos, k, r, lista);

            Request zahtev = new Request();
            zahtev.setData(iz); 
            zahtev.setOperation(Operacije.ADD_IZNAJMLJIVANJE);

            Komunikacija.getInstance().posaljiZahtev(zahtev);
            Response odgovor = Komunikacija.getInstance().primiOdgovor();

            boolean uspesno = (boolean) odgovor.getResult();
            if (uspesno) {
                JOptionPane.showMessageDialog(this, "Uspešno dodato iznajmljivanje!");
            } else {
                JOptionPane.showMessageDialog(this, "Greška prilikom dodavanja iznajmljivanja!");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Greška, morate popuniti sva polja!");
        }

    }//GEN-LAST:event_btnSacuvajIznajmljivanjeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DodajiznajmljivanjeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DodajiznajmljivanjeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DodajiznajmljivanjeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DodajiznajmljivanjeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DodajiznajmljivanjeForm dialog = new DodajiznajmljivanjeForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajStavku;
    private javax.swing.JButton btnObrisiStavku;
    private javax.swing.JButton btnOtkazi;
    private javax.swing.JButton btnSacuvajIznajmljivanje;
    private javax.swing.JComboBox cmbAutomobil;
    private javax.swing.JComboBox cmbKlijent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblStavkaIznajmljivanja;
    private javax.swing.JFormattedTextField txtDatumDo;
    private javax.swing.JFormattedTextField txtDatumOd;
    private javax.swing.JTextArea txtNapomena;
    private javax.swing.JTextArea txtOpis;
    // End of variables declaration//GEN-END:variables

    private void popuniAutomobile() {
        Request zahtev = new Request();
        zahtev.setOperation(Operacije.GET_ALL_AUTOMOBIL);
        Komunikacija.getInstance().posaljiZahtev(zahtev);
        Response odgovor = Komunikacija.getInstance().primiOdgovor();
        ArrayList<Automobil> lista = (ArrayList<Automobil>) odgovor.getResult();
        cmbAutomobil.removeAllItems();
        for (Automobil automobil : lista) {
            cmbAutomobil.addItem(automobil);
        }
    }

    private void popuniDostupneAutomobile() {
        System.out.println("popunjavam automobile!");
        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
        try {
            String datumOdText = txtDatumOd.getText().trim();
            String datumDoText = txtDatumDo.getText().trim();

            if (datumOdText.isEmpty() || datumDoText.isEmpty()) {
                return;
            }

            Date datumOd = sdf.parse(datumOdText);
            Date datumDo = sdf.parse(datumDoText);

            if (datumOd.after(datumDo)) {
                return;
            }

            ParametarDostupnihAutomobila parametar = new ParametarDostupnihAutomobila(datumOd, datumDo);
            Request zahtev = new Request();
            zahtev.setOperation(Operacije.GET_ALL_DOSTUPNE_AUTOMOBILE);
            zahtev.setData(parametar);

            Komunikacija.getInstance().posaljiZahtev(zahtev);
            Response odgovor = Komunikacija.getInstance().primiOdgovor();

            if (odgovor.getException() != null) {
                return;
            }

            ArrayList<Automobil> dostupni = (ArrayList<Automobil>) odgovor.getResult();
            cmbAutomobil.removeAllItems();
            for (Automobil a : dostupni) {
                cmbAutomobil.addItem(a);
            }

        } catch (ParseException | ClassCastException ex) {
            // format nije validan, ignoriši

        }
        cmbAutomobil.repaint();
        cmbAutomobil.revalidate();
    }

    private void popuniKlijente() {
        Request zahtev = new Request();
        zahtev.setOperation(Operacije.GET_ALL_KLIJENT);
        Komunikacija.getInstance().posaljiZahtev(zahtev);
        Response odgovor = Komunikacija.getInstance().primiOdgovor();
        ArrayList<Klijent> lista = (ArrayList<Klijent>) odgovor.getResult();
        cmbKlijent.removeAllItems();
        for (Klijent klijent : lista) {
            cmbKlijent.addItem(klijent);
        }
    }

    private boolean datumiSePreklapaju(Date pocetak1, Date kraj1, Date pocetak2, Date kraj2) {
        return !(kraj1.before(pocetak2) || kraj2.before(pocetak1));
    }
}
