/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forme;

import domain.Automobil;
import javax.swing.JOptionPane;
import kontroler.Komunikacija;
import transfer.Request;
import transfer.Response;
import transfer.util.Operacije;

/**
 *
 * @author mihajlodjordjevic
 */
public class DodajAutomobilForma extends javax.swing.JDialog {

    /**
     * Creates new form DodajAutomobilForma
     */
    public DodajAutomobilForma(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtMarkaAutomobila = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtModelAutomobila = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtRegBroj = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCenaPoDanu = new javax.swing.JFormattedTextField();
        btnDodajAutomobil = new javax.swing.JButton();
        btnOtkaziAutomobil = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Marka Automobila:");

        jLabel2.setText("Model Automobila:");

        jLabel3.setText("Registracioni Broj:");

        jLabel4.setText("Cena Po Danu:");

        txtCenaPoDanu.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        btnDodajAutomobil.setText("Dodaj Automobil");
        btnDodajAutomobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajAutomobilActionPerformed(evt);
            }
        });

        btnOtkaziAutomobil.setText("Otkazi");
        btnOtkaziAutomobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOtkaziAutomobilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMarkaAutomobila, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRegBroj)
                            .addComponent(txtModelAutomobila)
                            .addComponent(txtCenaPoDanu)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDodajAutomobil, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOtkaziAutomobil, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMarkaAutomobila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtModelAutomobila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtRegBroj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCenaPoDanu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDodajAutomobil)
                    .addComponent(btnOtkaziAutomobil))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDodajAutomobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajAutomobilActionPerformed
        String marka = txtMarkaAutomobila.getText().trim();
        String model = txtModelAutomobila.getText().trim();
        String regBr = txtRegBroj.getText().toUpperCase().trim();
        String cenaText = txtCenaPoDanu.getText().trim();

        // 1. Provera praznih polja
        if (marka.isEmpty() || model.isEmpty() || regBr.isEmpty() || cenaText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Sva polja moraju biti popunjena!", "Greška!", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 2. Provera registracije
        if (!regBr.matches("^[A-Z]{2}-\\d{3,5}-[A-Z]{2}$")) {
            JOptionPane.showMessageDialog(this, "Registarski broj mora biti u formatu XX-YYYY(Y)-XX !!", "Greška!", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 3. Provera cene
        double cenaPoDanu;
        try {
            cenaPoDanu = Double.parseDouble(cenaText);
            if (cenaPoDanu <= 0) {
                JOptionPane.showMessageDialog(this, "Cena po danu mora biti veća od 0!", "Greška!", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Cena po danu mora biti broj!", "Greška", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Automobil a = new Automobil(0, regBr, marka, model, cenaPoDanu);

        Request zahtev = new Request();
        zahtev.setData(a);
        zahtev.setOperation(Operacije.ADD_AUTOMOBIL);

        Komunikacija.getInstance().posaljiZahtev(zahtev);

        Response odgovor = Komunikacija.getInstance().primiOdgovor();

        boolean uspesno = (boolean) odgovor.getResult();

        if (uspesno) {
            JOptionPane.showMessageDialog(this, "Automobil je uspesno dodat!", "Uspesno", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Nije uspesno dodat automobil!", "Greška", JOptionPane.ERROR_MESSAGE);
            return;
        }

    }//GEN-LAST:event_btnDodajAutomobilActionPerformed

    private void btnOtkaziAutomobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOtkaziAutomobilActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnOtkaziAutomobilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DodajAutomobilForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DodajAutomobilForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DodajAutomobilForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DodajAutomobilForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DodajAutomobilForma dialog = new DodajAutomobilForma(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajAutomobil;
    private javax.swing.JButton btnOtkaziAutomobil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JFormattedTextField txtCenaPoDanu;
    private javax.swing.JTextField txtMarkaAutomobila;
    private javax.swing.JTextField txtModelAutomobila;
    private javax.swing.JFormattedTextField txtRegBroj;
    // End of variables declaration//GEN-END:variables
}
