/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forme;

import domain.Automobil;
import domain.Iznajmljivanje;
import domain.Klijent;
import domain.ParametarDostupnihAutomobila;
import domain.Radnik;
import domain.StavkaIznajmljivanja;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import kontroler.Komunikacija;
import modeli.ModelTabeleStavkaIznajmljivanja;
import transfer.Request;
import transfer.Response;
import transfer.util.Operacije;

/**
 *
 * @author mihajlodjordjevic
 */
public class IzmeniIznajmljivanjeForm extends javax.swing.JDialog {

    private Iznajmljivanje iz;
    private boolean izmenjeno = false;
    private ArrayList<Automobil> trenutnoDostupniAutomobili = new ArrayList<>();

    /**
     * Creates new form IzmeniIznajmljivanjeForm
     */
    public IzmeniIznajmljivanjeForm(java.awt.Frame parent, boolean modal, Iznajmljivanje iz) {
        super(parent, modal);
        initComponents();
        this.iz = iz;
        DocumentListener listener = new DocumentListener() {
            public void insertUpdate(DocumentEvent e) {
                popuniDostupneAutomobile();
            }

            public void removeUpdate(DocumentEvent e) {
                popuniDostupneAutomobile();
            }

            public void changedUpdate(DocumentEvent e) {
                popuniDostupneAutomobile();
            }
        };
        txtDatumOd.getDocument().addDocumentListener(listener);
        txtDatumDo.getDocument().addDocumentListener(listener);
        setLocationRelativeTo(null);
        popuniAutomobile();
        tblStavkaIznajmljivanja.setModel(new ModelTabeleStavkaIznajmljivanja());
        ModelTabeleStavkaIznajmljivanja mt = (ModelTabeleStavkaIznajmljivanja) tblStavkaIznajmljivanja.getModel();
        mt.setLista(iz.getStavkeIznajmljivanja());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDodajStavku = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtNapomena = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        cmbAutomobil = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtDatumOd = new javax.swing.JFormattedTextField();
        btnObrisiStavku = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtOpis = new javax.swing.JTextArea();
        txtDatumDo = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStavkaIznajmljivanja = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        btnSacuvaj = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnDodajStavku.setText("Dodaj Stavku Iznajmljivanja");
        btnDodajStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajStavkuActionPerformed(evt);
            }
        });

        txtNapomena.setColumns(20);
        txtNapomena.setRows(5);
        jScrollPane2.setViewportView(txtNapomena);

        jLabel2.setText("Automobil:");

        cmbAutomobil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbAutomobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAutomobilActionPerformed(evt);
            }
        });

        jLabel5.setText("Napomena:");

        jLabel3.setText("Datum Od:");

        txtDatumOd.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd.MM.yyyy"))));

        btnObrisiStavku.setText("Obrisi Stavku Iznajmljivanja");
        btnObrisiStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiStavkuActionPerformed(evt);
            }
        });

        jLabel4.setText("Datum Do:");

        txtOpis.setColumns(20);
        txtOpis.setRows(5);
        jScrollPane3.setViewportView(txtOpis);

        txtDatumDo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd.MM.yyyy"))));

        tblStavkaIznajmljivanja.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblStavkaIznajmljivanja);

        jLabel6.setText("Opis:");

        btnSacuvaj.setText("Sacuvaj izmenu");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        jButton1.setText("Zatvori");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtDatumDo, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnDodajStavku)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnObrisiStavku)
                                .addGap(8, 8, 8))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbAutomobil, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDatumOd, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnSacuvaj, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addGap(18, 18, 18)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbAutomobil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDatumOd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDatumDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDodajStavku, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnObrisiStavku, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSacuvaj)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDodajStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajStavkuActionPerformed

        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
        try {

            Automobil automobil = (Automobil) cmbAutomobil.getSelectedItem();
            String datumOdText = txtDatumOd.getText();
            String datumDoText = txtDatumDo.getText();
            String napomena = txtNapomena.getText();

            if (automobil == null || datumOdText.isEmpty() || datumDoText.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Sva polja moraju biti popunjena!", "Greska!", JOptionPane.ERROR_MESSAGE);
                return;
            }

            Date datumOd = sdf.parse(datumOdText);
            Date datumDo = sdf.parse(datumDoText);

            if (datumOd.after(datumDo)) {
                JOptionPane.showMessageDialog(this, "Datum OD mora biti pre datuma DO!", "Greška!", JOptionPane.ERROR_MESSAGE);
                return;
            }

            int brojDana = (int) (datumDo.getTime() - datumOd.getTime()) / (1000 * 60 * 60 * 24);
            if (brojDana == 0) {
                brojDana = 1;
            }
            ModelTabeleStavkaIznajmljivanja mt = (ModelTabeleStavkaIznajmljivanja) tblStavkaIznajmljivanja.getModel();
            double cena = brojDana * automobil.getCenaPoDanu();
            int rb = mt.getRowCount() + 1;
            for (int i = 0; i < mt.getRowCount(); i++) {
                StavkaIznajmljivanja si = mt.getStavkaAt(i);
                Automobil a = si.getAutomobi();

                if (a.getAutomobilID() == automobil.getAutomobilID()
                        && datumiSePreklapaju(si.getDatumOd(), si.getDatumDo(), datumOd, datumDo)) {
                    JOptionPane.showMessageDialog(this, "Automobil je već dodat za izabrani termin.");
                    return;
                }
            }
            StavkaIznajmljivanja stavkaIznajmljivanja = new StavkaIznajmljivanja(null, rb, napomena, datumOd, datumDo, brojDana, cena, automobil);
            mt.dodajStavku(stavkaIznajmljivanja);

            if (trenutnoDostupniAutomobili != null) {
                trenutnoDostupniAutomobili.removeIf(a -> a.getAutomobilID() == automobil.getAutomobilID());

                cmbAutomobil.removeAllItems();
                for (Automobil a : trenutnoDostupniAutomobili) {
                    cmbAutomobil.addItem(a);
                }
            }

            txtDatumDo.setText("");
            txtDatumOd.setText("");
            txtNapomena.setText("");
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "Greska!");
        }
    }//GEN-LAST:event_btnDodajStavkuActionPerformed

    private void cmbAutomobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAutomobilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbAutomobilActionPerformed

    private void btnObrisiStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiStavkuActionPerformed
        int selectedRow = tblStavkaIznajmljivanja.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Morate izabrati stavku za brisanje!", "Greška!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        ModelTabeleStavkaIznajmljivanja mt = (ModelTabeleStavkaIznajmljivanja) tblStavkaIznajmljivanja.getModel();
        StavkaIznajmljivanja obrisana = mt.getStavkaAt(selectedRow);
        mt.obrisiStavku(selectedRow);

        Automobil obrisanAuto = obrisana.getAutomobi();

        boolean postoji = false;
        for (Automobil a : trenutnoDostupniAutomobili) {
            if (a.getAutomobilID() == obrisanAuto.getAutomobilID()) {
                postoji = true;
                break;
            }
        }
        if (!postoji) {
            trenutnoDostupniAutomobili.add(obrisanAuto);
        }
        cmbAutomobil.removeAllItems();
        for (Automobil a : trenutnoDostupniAutomobili) {
            cmbAutomobil.addItem(a);
        }
        mt.fireTableDataChanged();


    }//GEN-LAST:event_btnObrisiStavkuActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed
        try {
            String opis = txtOpis.getText();
            double ukupanIznos = 0;

            ModelTabeleStavkaIznajmljivanja mt = (ModelTabeleStavkaIznajmljivanja) tblStavkaIznajmljivanja.getModel();
            ArrayList<StavkaIznajmljivanja> lista = mt.getLista();

            for (StavkaIznajmljivanja stavkaIznajmljivanja : lista) {
                ukupanIznos += stavkaIznajmljivanja.getCena();
            }

            iz.setDatumVreme(new Date());
            iz.setOpis(opis);
            iz.setUkupanIznos(ukupanIznos);
            iz.setStavkeIznajmljivanja(lista);
            //  Dodaj direktno stavke prilikom pravljenja objekta
//            Iznajmljivanje iz = new Iznajmljivanje(-1, new Date(), opis, ukupanIznos, k, r, lista);

            Request zahtev = new Request();
            zahtev.setData(iz);
            zahtev.setOperation(Operacije.UPDATE_IZNAJMLJIVANJE);

            Komunikacija.getInstance().posaljiZahtev(zahtev);
            Response odgovor = Komunikacija.getInstance().primiOdgovor();

            boolean uspesno = (boolean) odgovor.getResult();
            if (uspesno) {
                JOptionPane.showMessageDialog(this, "Uspešno izmenjeno iznajmljivanje!");
            } else {
                JOptionPane.showMessageDialog(this, "Greška prilikom izmene iznajmljivanja!");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Doslo je do neke greske prilikom izmenjivanja random");
        }
    }//GEN-LAST:event_btnSacuvajActionPerformed

    public boolean isIzmenjeno() {
        return izmenjeno;
    }

    private boolean datumiSePreklapaju(Date pocetak1, Date kraj1, Date pocetak2, Date kraj2) {
        return !(kraj1.before(pocetak2) || kraj2.before(pocetak1));
    }

    private void popuniDostupneAutomobile() {

        System.out.println("popunjavam automobile!");
        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
        try {
            String datumOdText = txtDatumOd.getText().trim();
            String datumDoText = txtDatumDo.getText().trim();

            if (datumOdText.isEmpty() || datumDoText.isEmpty()) {
                return;
            }

            Date datumOd = sdf.parse(datumOdText);
            Date datumDo = sdf.parse(datumDoText);

            if (datumOd.after(datumDo)) {
                return;
            }

            ParametarDostupnihAutomobila parametar = new ParametarDostupnihAutomobila(datumOd, datumDo);
            Request zahtev = new Request();
            zahtev.setOperation(Operacije.GET_ALL_DOSTUPNE_AUTOMOBILE);
            zahtev.setData(parametar);

            Komunikacija.getInstance().posaljiZahtev(zahtev);
            Response odgovor = Komunikacija.getInstance().primiOdgovor();

            if (odgovor.getException() != null) {
                return;
            }

            ArrayList<Automobil> dostupni = (ArrayList<Automobil>) odgovor.getResult();
            cmbAutomobil.removeAllItems();
            for (Automobil a : dostupni) {
                cmbAutomobil.addItem(a);
            }

            trenutnoDostupniAutomobili.clear();
            trenutnoDostupniAutomobili.addAll(dostupni);

        } catch (ParseException | ClassCastException ex) {
            // format nije validan, ignoriši

        }
        cmbAutomobil.repaint();
        cmbAutomobil.revalidate();
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajStavku;
    private javax.swing.JButton btnObrisiStavku;
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JComboBox cmbAutomobil;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblStavkaIznajmljivanja;
    private javax.swing.JFormattedTextField txtDatumDo;
    private javax.swing.JFormattedTextField txtDatumOd;
    private javax.swing.JTextArea txtNapomena;
    private javax.swing.JTextArea txtOpis;
    // End of variables declaration//GEN-END:variables

    private void popuniAutomobile() {
        Request zahtev = new Request();
        zahtev.setOperation(Operacije.GET_ALL_AUTOMOBIL);
        Komunikacija.getInstance().posaljiZahtev(zahtev);
        Response odgovor = Komunikacija.getInstance().primiOdgovor();
        ArrayList<Automobil> lista = (ArrayList<Automobil>) odgovor.getResult();
        cmbAutomobil.removeAllItems();
        for (Automobil automobil : lista) {
            cmbAutomobil.addItem(automobil);
        }
    }

    private void popuniTabelu() {

    }
}
