/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forme;

import domain.Automobil;
import javax.swing.JOptionPane;
import kontroler.Komunikacija;
import transfer.Request;
import transfer.Response;
import transfer.util.Operacije;
import transfer.util.ResponseStatus;

/**
 *
 * @author mihajlodjordjevic
 */
public class IzmeniAutomobilForm extends javax.swing.JDialog {

    private Automobil automobil;
    private boolean izmenjeno = false;

    /**
     * Creates new form IzmeniAutomobilForm
     */
    public IzmeniAutomobilForm(java.awt.Frame parent, boolean modal, Automobil automobil) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.automobil = automobil;
        popuniPolja();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtRegistarskiBroj = new javax.swing.JTextField();
        txtCenaPoDanu = new javax.swing.JFormattedTextField();
        btnSacuvaj = new javax.swing.JButton();
        btnOtkazi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Registarski Broj:");

        jLabel2.setText("Cena Po Danu:");

        txtCenaPoDanu.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        btnSacuvaj.setText("Sacuvaj");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        btnOtkazi.setText("Otkazi");
        btnOtkazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOtkaziActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCenaPoDanu)
                            .addComponent(txtRegistarskiBroj)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(btnSacuvaj, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addComponent(btnOtkazi, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtRegistarskiBroj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCenaPoDanu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOtkazi)
                    .addComponent(btnSacuvaj))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOtkaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOtkaziActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnOtkaziActionPerformed

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed
        String regBr = txtRegistarskiBroj.getText();
        String cena = txtCenaPoDanu.getText();
        if (regBr.isEmpty() || cena.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Sva polja moraju biti popunjena!", "Greska!", JOptionPane.ERROR_MESSAGE);
            return;
        }

        double cenaPoDanu;
        try {
            cenaPoDanu = Double.parseDouble(cena);
            if (cenaPoDanu <= 0) {
                JOptionPane.showMessageDialog(this, "Cena mora biti veca od nule!", "Greska!", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Cena mora biti broj!", "Greška", JOptionPane.ERROR_MESSAGE);
            return;
        }
        this.automobil.setRegistarskiBroj(regBr);
        this.automobil.setCenaPoDanu(cenaPoDanu);

        Request zahtev = new Request();
        zahtev.setData(automobil);
        zahtev.setOperation(Operacije.UPDATE_AUTOMOBIL);
        try {
            Komunikacija.getInstance().posaljiZahtev(zahtev);

            Response odgovor = Komunikacija.getInstance().primiOdgovor();

            if (odgovor.getStatus() == ResponseStatus.Success && (boolean) odgovor.getResult()) {
                izmenjeno = true;
                JOptionPane.showMessageDialog(this, "Uspesno izmenjen automobil!");
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Izmena nije uspela!", "Greska!", JOptionPane.ERROR_MESSAGE);
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Greska prilikom izmene: " + ex.getMessage(), "Greska!", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnSacuvajActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOtkazi;
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JFormattedTextField txtCenaPoDanu;
    private javax.swing.JTextField txtRegistarskiBroj;
    // End of variables declaration//GEN-END:variables

    private void popuniPolja() {
        txtRegistarskiBroj.setText(this.automobil.getRegistarskiBroj());
        txtCenaPoDanu.setText(String.valueOf(this.automobil.getCenaPoDanu()));
    }

    public boolean isIzmenjeno() {
        return izmenjeno;
    }

    public void setIzmenjeno(boolean izmenjeno) {
        this.izmenjeno = izmenjeno;
    }

}
