/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forme;

import domain.Automobil;
import domain.Iznajmljivanje;
import domain.ParametarDostupnihAutomobila;
import domain.StavkaIznajmljivanja;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import kontroler.Komunikacija;
import transfer.Request;
import transfer.Response;
import transfer.util.Operacije;

/**
 *
 * @author mihajlodjordjevic
 */
public class IzmeniStavkuIznajmljivanjaForm extends javax.swing.JDialog {

    private StavkaIznajmljivanja stavka;

    /**
     * Creates new form IzmeniStavkuIznajmljivanjaForm
     */
    public IzmeniStavkuIznajmljivanjaForm(java.awt.Frame parent, boolean modal, StavkaIznajmljivanja stavka) {
        super(parent, modal);
        this.stavka = stavka;
        initComponents();
        setLocationRelativeTo(null);
        popuniAutomobile();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbAutomobil = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        txtDatumOd = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDatumDo = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtNapomena = new javax.swing.JTextArea();
        btnSacuvaj = new javax.swing.JButton();
        btnOtkazi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Automobil:");

        cmbAutomobil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Datum od:");

        txtDatumOd.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd.MM.yyyy"))));

        jLabel3.setText("Datum do:");

        txtDatumDo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd.MM.yyyy"))));
        txtDatumDo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDatumDoActionPerformed(evt);
            }
        });

        jLabel4.setText("Napomena:");

        txtNapomena.setColumns(20);
        txtNapomena.setRows(5);
        jScrollPane1.setViewportView(txtNapomena);

        btnSacuvaj.setText("Sacuvaj izmenu");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        btnOtkazi.setText("Otkazi");
        btnOtkazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOtkaziActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbAutomobil, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDatumOd))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDatumDo)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSacuvaj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOtkazi)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbAutomobil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDatumOd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDatumDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSacuvaj)
                    .addComponent(btnOtkazi))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDatumDoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDatumDoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDatumDoActionPerformed

    private void btnOtkaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOtkaziActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnOtkaziActionPerformed

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed
        try {
            Automobil a = (Automobil) cmbAutomobil.getSelectedItem();

            if (txtDatumOd.getText().isEmpty() || txtDatumDo.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Morate uneti oba datuma!");
                return;
            }

            SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
            Date datumOd = sdf.parse(txtDatumOd.getText());
            Date datumDo = sdf.parse(txtDatumDo.getText());
            String napomena = txtNapomena.getText();

            if (datumDo.before(datumOd)) {
                JOptionPane.showMessageDialog(this, "Datum do mora biti posle datuma od!", "Greska!", JOptionPane.ERROR_MESSAGE);
                return;
            }

            ParametarDostupnihAutomobila parametar = new ParametarDostupnihAutomobila(datumOd, datumDo);
            Request zahtevProvera = new Request();
            zahtevProvera.setData(parametar);
            zahtevProvera.setOperation(Operacije.GET_ALL_DOSTUPNE_AUTOMOBILE);
            Komunikacija.getInstance().posaljiZahtev(zahtevProvera);
            Response odgovorProvera = Komunikacija.getInstance().primiOdgovor();
            ArrayList<Automobil> dostupniAutomobili = (ArrayList<Automobil>) odgovorProvera.getResult();

//            System.out.println("Dostupni automobili u izabranom periodu:");
//            for (Automobil auto : dostupniAutomobili) {
//                System.out.println(auto.getAutomobilID() + " - " + auto.getMarka() + " " + auto.getModel() + ", cena: " + auto.getCenaPoDanu());
//            }
            if (!dostupniAutomobili.contains(a)) {
                if (a.getAutomobilID() == stavka.getAutomobi().getAutomobilID()) {
                    JOptionPane.showMessageDialog(this,
                            "Ako želite da promenite datum za ovaj auto u periodu koji se preklapa sa trenutnim, "
                            + "moraćete prvo da obrišete ovo iznajmljivanje!",
                            "Greska!", JOptionPane.ERROR_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this,
                            "Automobil je zauzet u izabranom periodu!",
                            "Greska!", JOptionPane.ERROR_MESSAGE);
                }
                return;
            }

            stavka.setAutomobi(a);
            stavka.setDatumOd(datumOd);
            stavka.setDatumDo(datumDo);
            stavka.setBrojDana((int) ((datumDo.getTime() - datumOd.getTime()) / (1000 * 60 * 60 * 24)));
            stavka.setCena(stavka.getBrojDana() * a.getCenaPoDanu());
            stavka.setNapomena(napomena);

            Request zahtev1 = new Request();
            zahtev1.setData(stavka);
            zahtev1.setOperation(Operacije.UPDATE_STAVKA_IZNAJMLJIVANJA);
            Komunikacija.getInstance().posaljiZahtev(zahtev1);
            Komunikacija.getInstance().primiOdgovor();

            Request zahtevSveStavke = new Request();
            StavkaIznajmljivanja kriterijum = new StavkaIznajmljivanja();
            kriterijum.setIznajmljivanje(stavka.getIznajmljivanje());
            zahtevSveStavke.setData(kriterijum);
            zahtevSveStavke.setOperation(Operacije.GET_ALL_STAVKA_IZNAJMLJIVANJA);
            Komunikacija.getInstance().posaljiZahtev(zahtevSveStavke);
            Response odgovorSveStavke = Komunikacija.getInstance().primiOdgovor();
            ArrayList<StavkaIznajmljivanja> stavke = (ArrayList<StavkaIznajmljivanja>) odgovorSveStavke.getResult();

            double ukupno = 0;
            for (StavkaIznajmljivanja si : stavke) {
                ukupno += si.getCena();
            }

            System.out.println("Izracunato ukupno: " + ukupno);

//            Iznajmljivanje iz = stavka.getIznajmljivanje();
//            iz.setUkupanIznos(ukupno);
            Iznajmljivanje zaSlanje = new Iznajmljivanje();
            zaSlanje.setIznajmljivanjeID(stavka.getIznajmljivanje().getIznajmljivanjeID());
            zaSlanje.setUkupanIznos(ukupno);

            Request zahtev2 = new Request();
            zahtev2.setData(zaSlanje);
            System.out.println("Pripremljeno za slanje: " + zaSlanje.getUkupanIznos());
            zahtev2.setOperation(Operacije.UPDATE_IZNAJMLJIVANJE);
            Komunikacija.getInstance().posaljiZahtev(zahtev2);
            Komunikacija.getInstance().primiOdgovor();

            JOptionPane.showMessageDialog(this, "Iznajmljivanje uspesno promenjeno");

            for (java.awt.Window window : java.awt.Window.getWindows()) {
                if (window instanceof javax.swing.JFrame && !(window instanceof KlijentskaForma)) {
                    window.dispose();
                }
            }

        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Greska prilikom izmene stavke!", "Greska!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSacuvajActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(IzmeniStavkuIznajmljivanjaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(IzmeniStavkuIznajmljivanjaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(IzmeniStavkuIznajmljivanjaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(IzmeniStavkuIznajmljivanjaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                IzmeniStavkuIznajmljivanjaForm dialog = new IzmeniStavkuIznajmljivanjaForm(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOtkazi;
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JComboBox cmbAutomobil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JFormattedTextField txtDatumDo;
    private javax.swing.JFormattedTextField txtDatumOd;
    private javax.swing.JTextArea txtNapomena;
    // End of variables declaration//GEN-END:variables

    private void popuniAutomobile() {
        try {
            Request zahtev = new Request();
            zahtev.setOperation(Operacije.GET_ALL_AUTOMOBIL);
            Komunikacija.getInstance().posaljiZahtev(zahtev);
            Response odgovor = Komunikacija.getInstance().primiOdgovor();

            ArrayList<Automobil> listaAutomobila = (ArrayList<Automobil>) odgovor.getResult();
            cmbAutomobil.removeAllItems();

            for (Automobil automobil : listaAutomobila) {
                cmbAutomobil.addItem(automobil);
                if (automobil.getAutomobilID() == stavka.getAutomobi().getAutomobilID()) {
                    cmbAutomobil.setSelectedItem(automobil);
                }
            }
            txtDatumOd.setText(new SimpleDateFormat("dd.MM.yyyy").format(stavka.getDatumOd()));
            txtDatumDo.setText(new SimpleDateFormat("dd.MM.yyyy").format(stavka.getDatumDo()));
            txtNapomena.setText(stavka.getNapomena());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Greska prilikom popunjavanja automobila!", "Greska!", JOptionPane.ERROR_MESSAGE);
        }
    }
}
