/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import javax.swing.JOptionPane;
import kontroler.Komunikacija;
import transfer.Request;
import transfer.Response;
import transfer.util.Operacije;

/**
 *
 * @author mihajlodjordjevic
 */
public class KlijentskaForma extends javax.swing.JFrame {

    /**
     * Creates new form KlijentskaForma
     */
    public KlijentskaForma() {
        setLocationRelativeTo(null);
        initComponents();
        lblUlogovani.setText(Komunikacija.getInstance().getZaposleni().getIme());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        lblUlogovani = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuItemIznajmljivanje = new javax.swing.JMenu();
        menuItemDodajNovoIznajmljivanje = new javax.swing.JMenuItem();
        menuItemPretraziIznajmljivanja = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        menuItemDodajKlijenta = new javax.swing.JMenuItem();
        menuItemPretraziKlijente = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        menuItemDodajAutomobil = new javax.swing.JMenuItem();
        menuItemPretraziAutomobile = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        miPregled = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        menuItemLogout = new javax.swing.JMenuItem();
        menuItemZatvori = new javax.swing.JMenuItem();
        menuItemPomoc = new javax.swing.JMenu();
        MenuItemAbout = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ulogovani:");

        lblUlogovani.setText("jLabel2");

        jLabel2.setFont(new java.awt.Font(".AppleSystemUIFont", 3, 14)); // NOI18N
        jLabel2.setText("DOBRODOSLI U APLIKACIJU ZA RENTIRANJE AUTOMOBILA!");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/pngwing.com-2.png"))); // NOI18N

        menuItemIznajmljivanje.setText("Iznajmljivanje");
        menuItemIznajmljivanje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemIznajmljivanjeActionPerformed(evt);
            }
        });

        menuItemDodajNovoIznajmljivanje.setText("Dodaj novo Iznajmljivanje");
        menuItemDodajNovoIznajmljivanje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemDodajNovoIznajmljivanjeActionPerformed(evt);
            }
        });
        menuItemIznajmljivanje.add(menuItemDodajNovoIznajmljivanje);

        menuItemPretraziIznajmljivanja.setText("Pretrazi Iznajmljivanja");
        menuItemPretraziIznajmljivanja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPretraziIznajmljivanjaActionPerformed(evt);
            }
        });
        menuItemIznajmljivanje.add(menuItemPretraziIznajmljivanja);

        jMenuBar1.add(menuItemIznajmljivanje);

        jMenu5.setText("Klijent");

        menuItemDodajKlijenta.setText("Dodaj Klijenta");
        menuItemDodajKlijenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemDodajKlijentaActionPerformed(evt);
            }
        });
        jMenu5.add(menuItemDodajKlijenta);

        menuItemPretraziKlijente.setText("Pretrazi Klijente");
        menuItemPretraziKlijente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPretraziKlijenteActionPerformed(evt);
            }
        });
        jMenu5.add(menuItemPretraziKlijente);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Automobil");

        menuItemDodajAutomobil.setText("Dodaj Automobil");
        menuItemDodajAutomobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemDodajAutomobilActionPerformed(evt);
            }
        });
        jMenu6.add(menuItemDodajAutomobil);

        menuItemPretraziAutomobile.setText("Pretrazi Automobile");
        menuItemPretraziAutomobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPretraziAutomobileActionPerformed(evt);
            }
        });
        jMenu6.add(menuItemPretraziAutomobile);

        jMenuBar1.add(jMenu6);

        jMenu1.setText("Radnici");

        miPregled.setText("Pregled radnika");
        miPregled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPregledActionPerformed(evt);
            }
        });
        jMenu1.add(miPregled);

        jMenuBar1.add(jMenu1);

        jMenu9.setText("Opcije");

        menuItemLogout.setText("Logout");
        menuItemLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemLogoutActionPerformed(evt);
            }
        });
        jMenu9.add(menuItemLogout);

        menuItemZatvori.setText("Zatvori");
        menuItemZatvori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemZatvoriActionPerformed(evt);
            }
        });
        jMenu9.add(menuItemZatvori);

        jMenuBar1.add(jMenu9);

        menuItemPomoc.setText("  Pomoc");
        menuItemPomoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPomocActionPerformed(evt);
            }
        });

        MenuItemAbout.setText("O programu");
        MenuItemAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemAboutActionPerformed(evt);
            }
        });
        menuItemPomoc.add(MenuItemAbout);

        jMenuBar1.add(menuItemPomoc);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(34, 34, 34)
                                .addComponent(lblUlogovani))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblUlogovani))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemZatvoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemZatvoriActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuItemZatvoriActionPerformed

    private void menuItemLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemLogoutActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, "Da li ste sigurni?", "Logout", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            Request zahtev = new Request();
            zahtev.setData(Komunikacija.getInstance().getZaposleni());
            zahtev.setOperation(Operacije.LOGOUT);

            Komunikacija.getInstance().posaljiZahtev(zahtev);

            Response odgovor = Komunikacija.getInstance().primiOdgovor();

            if ((boolean) odgovor.getResult()) {
                Komunikacija.getInstance().setZaposleni(null);
                LoginForma lf = new LoginForma();
                this.dispose();
                lf.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "GRESKA!");
            }
        }
    }//GEN-LAST:event_menuItemLogoutActionPerformed

    private void menuItemIznajmljivanjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemIznajmljivanjeActionPerformed
        //Odradjeno
    }//GEN-LAST:event_menuItemIznajmljivanjeActionPerformed

    private void menuItemPomocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemPomocActionPerformed
        //NE TREBA NAM
    }//GEN-LAST:event_menuItemPomocActionPerformed

    private void MenuItemAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemAboutActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "AutoRent – Sistem za iznajmljivanje vozila\n"
                + "Verzija 1.0.0\n"
                + "Autor: Mihajlo Đorđević\n"
                + "Kontakt: +381645308148\n"
                + "Jun 2025.",
                "O programu",
                JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_MenuItemAboutActionPerformed

    private void menuItemDodajAutomobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemDodajAutomobilActionPerformed
        DodajAutomobilForma df = new DodajAutomobilForma(this, true);
        df.setVisible(true);
    }//GEN-LAST:event_menuItemDodajAutomobilActionPerformed

    private void menuItemPretraziAutomobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemPretraziAutomobileActionPerformed
        PretragaAutomobilaForm pf = new PretragaAutomobilaForm();
        pf.setVisible(true);
    }//GEN-LAST:event_menuItemPretraziAutomobileActionPerformed

    private void menuItemDodajKlijentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemDodajKlijentaActionPerformed
        DodajKlijentaForm dkf = new DodajKlijentaForm(this, true);
        dkf.setVisible(true);
    }//GEN-LAST:event_menuItemDodajKlijentaActionPerformed

    private void menuItemDodajNovoIznajmljivanjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemDodajNovoIznajmljivanjeActionPerformed
        DodajiznajmljivanjeForm dif = new DodajiznajmljivanjeForm(this, true);
        dif.setVisible(true);
    }//GEN-LAST:event_menuItemDodajNovoIznajmljivanjeActionPerformed

    private void menuItemPretraziKlijenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemPretraziKlijenteActionPerformed
        // TODO add your handling code here:
        PretragaKlijenataForm pkf = new PretragaKlijenataForm();
        pkf.setVisible(true);
    }//GEN-LAST:event_menuItemPretraziKlijenteActionPerformed

    private void menuItemPretraziIznajmljivanjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemPretraziIznajmljivanjaActionPerformed
        PretragaIznajmljivanjaForm pif = new PretragaIznajmljivanjaForm();
        pif.setVisible(true);
    }//GEN-LAST:event_menuItemPretraziIznajmljivanjaActionPerformed

    private void miPregledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPregledActionPerformed
        PrikaziRadnike pr = new PrikaziRadnike();
        pr.setVisible(true);
    }//GEN-LAST:event_miPregledActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KlijentskaForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuItemAbout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JLabel lblUlogovani;
    private javax.swing.JMenuItem menuItemDodajAutomobil;
    private javax.swing.JMenuItem menuItemDodajKlijenta;
    private javax.swing.JMenuItem menuItemDodajNovoIznajmljivanje;
    private javax.swing.JMenu menuItemIznajmljivanje;
    private javax.swing.JMenuItem menuItemLogout;
    private javax.swing.JMenu menuItemPomoc;
    private javax.swing.JMenuItem menuItemPretraziAutomobile;
    private javax.swing.JMenuItem menuItemPretraziIznajmljivanja;
    private javax.swing.JMenuItem menuItemPretraziKlijente;
    private javax.swing.JMenuItem menuItemZatvori;
    private javax.swing.JMenuItem miPregled;
    // End of variables declaration//GEN-END:variables
}
