/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import domain.Automobil;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import kontroler.Komunikacija;
import modeli.ModelTabeleAutomobili;
import transfer.Request;
import transfer.Response;
import transfer.util.Operacije;
import transfer.util.ResponseStatus;

/**
 *
 * @author mihajlodjordjevic
 */
public class PretragaAutomobilaForm extends javax.swing.JFrame {

    ArrayList<Automobil> sviAutomobili = new ArrayList<>();

    /**
     * Creates new form PretragaAutomobilaForm
     */
    public PretragaAutomobilaForm() {
        initComponents();
        setLocationRelativeTo(null);
        ucitajTabelu();

        //LISTENERI
        txtMarkaAutomobila.getDocument().addDocumentListener(new DocumentListener() {
            public void insertUpdate(DocumentEvent e) {
                filtrirajAutomobile();
            }

            public void removeUpdate(DocumentEvent e) {
                filtrirajAutomobile();
            }

            public void changedUpdate(DocumentEvent e) {
                filtrirajAutomobile();
            }
        });
        cbMarkaAutomobila.addItemListener(e -> filtrirajAutomobile());

        cbCenaPoDanuAutomobila.addItemListener(e -> filtrirajAutomobile());
        txtCenaPoDanuAutomobila.addPropertyChangeListener("value", evt -> filtrirajAutomobile());

        btnResetujFiltere.addActionListener(e -> {
            txtMarkaAutomobila.setText("");
            txtCenaPoDanuAutomobila.setText(null);
            cbCenaPoDanuAutomobila.setSelected(false);
            cbMarkaAutomobila.setSelected(false);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbMarkaAutomobila = new javax.swing.JCheckBox();
        cbCenaPoDanuAutomobila = new javax.swing.JCheckBox();
        txtMarkaAutomobila = new javax.swing.JTextField();
        txtCenaPoDanuAutomobila = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAutomobili = new javax.swing.JTable();
        btnIzmeniAutomobil = new javax.swing.JButton();
        btnObrisiAutomobil = new javax.swing.JButton();
        btnZatvoriPretragu = new javax.swing.JButton();
        btnResetujFiltere = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cbMarkaAutomobila.setText("Marka:");

        cbCenaPoDanuAutomobila.setText("Cena po danu:");

        txtCenaPoDanuAutomobila.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        tblAutomobili.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblAutomobili);

        btnIzmeniAutomobil.setText("Izmeni Automobil");
        btnIzmeniAutomobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniAutomobilActionPerformed(evt);
            }
        });

        btnObrisiAutomobil.setText("Obrisi Automobil");
        btnObrisiAutomobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiAutomobilActionPerformed(evt);
            }
        });

        btnZatvoriPretragu.setText("Zatvori");
        btnZatvoriPretragu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZatvoriPretraguActionPerformed(evt);
            }
        });

        btnResetujFiltere.setText("Resetuj filtere");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbCenaPoDanuAutomobila)
                            .addComponent(cbMarkaAutomobila))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMarkaAutomobila)
                            .addComponent(txtCenaPoDanuAutomobila)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnObrisiAutomobil, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnIzmeniAutomobil, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                            .addComponent(btnZatvoriPretragu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(228, 228, 228)
                .addComponent(btnResetujFiltere, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbMarkaAutomobila)
                    .addComponent(txtMarkaAutomobila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbCenaPoDanuAutomobila)
                    .addComponent(txtCenaPoDanuAutomobila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnResetujFiltere)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnIzmeniAutomobil)
                        .addGap(18, 18, 18)
                        .addComponent(btnObrisiAutomobil)
                        .addGap(18, 18, 18)
                        .addComponent(btnZatvoriPretragu)))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnZatvoriPretraguActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZatvoriPretraguActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnZatvoriPretraguActionPerformed

    private void btnObrisiAutomobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiAutomobilActionPerformed
        int selectedRow = tblAutomobili.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Izaberi automobil za brisanje!");
        }
        Automobil a = ((ModelTabeleAutomobili) tblAutomobili.getModel()).getAutomobilAt(selectedRow);

        int confirm = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da zelite da izbrisete ovaj automobil?", "Potvrda brisanja", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }
        try {
            Request zahtev = new Request();
            zahtev.setOperation(Operacije.DELETE_AUTOMOBIL);
            zahtev.setData(a);

            Komunikacija.getInstance().posaljiZahtev(zahtev);
            Response odgovor = Komunikacija.getInstance().primiOdgovor();

            if (odgovor.getStatus() == ResponseStatus.Success && odgovor.getResult() != null && (boolean) odgovor.getResult()) {
                JOptionPane.showMessageDialog(this, "Automobil uspešno obrisan.");
                sviAutomobili.remove(a); // uklanjamo i lokalno
                filtrirajAutomobile();   // osvežimo prikaz
            } else {
                String poruka = odgovor.getException() != null ? odgovor.getException().getMessage() : "Brisanje nije uspelo.";
                JOptionPane.showMessageDialog(this, poruka, "Greška", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Greska prilikom brisanja!", "Greska", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnObrisiAutomobilActionPerformed

    private void btnIzmeniAutomobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniAutomobilActionPerformed
        int selectedRow = tblAutomobili.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Izaberi automobil za brisanje!");
        }
        Automobil a = ((ModelTabeleAutomobili) tblAutomobili.getModel()).getAutomobilAt(selectedRow);
        IzmeniAutomobilForm iaf = new IzmeniAutomobilForm(this, true,a);
        iaf.setVisible(true);
        if(iaf.isIzmenjeno()){
            tblAutomobili.repaint();
            ((ModelTabeleAutomobili)tblAutomobili.getModel()).fireTableDataChanged();
        }
    }//GEN-LAST:event_btnIzmeniAutomobilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PretragaAutomobilaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PretragaAutomobilaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PretragaAutomobilaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PretragaAutomobilaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PretragaAutomobilaForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeniAutomobil;
    private javax.swing.JButton btnObrisiAutomobil;
    private javax.swing.JButton btnResetujFiltere;
    private javax.swing.JButton btnZatvoriPretragu;
    private javax.swing.JCheckBox cbCenaPoDanuAutomobila;
    private javax.swing.JCheckBox cbMarkaAutomobila;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAutomobili;
    private javax.swing.JFormattedTextField txtCenaPoDanuAutomobila;
    private javax.swing.JTextField txtMarkaAutomobila;
    // End of variables declaration//GEN-END:variables

    private void ucitajTabelu() {
        try {
            Request zahtev = new Request();
            zahtev.setOperation(Operacije.GET_ALL_AUTOMOBIL);
            Komunikacija.getInstance().posaljiZahtev(zahtev);
            Response odgovor = Komunikacija.getInstance().primiOdgovor();
            sviAutomobili = (ArrayList<Automobil>) odgovor.getResult();

            filtrirajAutomobile();
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Greska prilikom ucitavanja automobila!", "Greska", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void filtrirajAutomobile() {
        if (sviAutomobili == null) {
            return;
        }
        ArrayList<Automobil> filtrirani = new ArrayList<>(sviAutomobili);

        if (cbMarkaAutomobila.isSelected()) {
            String marka = txtMarkaAutomobila.getText().trim().toLowerCase();
            filtrirani.removeIf(a -> !a.getMarka().toLowerCase().contains(marka));
        }

        if (cbCenaPoDanuAutomobila.isSelected()) {
            try {
                String cenaText = txtCenaPoDanuAutomobila.getText().trim();
                if (!cenaText.isEmpty()) {
                    double cena = Double.parseDouble(cenaText);
                    filtrirani.removeIf(a -> a.getCenaPoDanu() > cena);
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Unesite ispravnu cenu!", "Greska!", JOptionPane.WARNING_MESSAGE);
            }

        }
        tblAutomobili.setModel(new ModelTabeleAutomobili(filtrirani));

    }
}
