/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import domain.Iznajmljivanje;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import kontroler.Komunikacija;
import modeli.ModelTabeleAutomobili;
import modeli.ModelTabeleIznajmljivanja;
import transfer.Request;
import transfer.Response;
import transfer.util.Operacije;

/**
 *
 * @author mihajlodjordjevic
 */
public class PretragaIznajmljivanjaForm extends javax.swing.JFrame {

    private ArrayList<Iznajmljivanje> svaIznajmljivanja;

    /**
     * Creates new form PretragaIznajmljivanjaForm
     */
    public PretragaIznajmljivanjaForm() {
        initComponents();
        setLocationRelativeTo(null);
        ucitajIznajmljivanja();

        txtKlijent.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                filtrirajIznajmljivanja();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                filtrirajIznajmljivanja();

            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                filtrirajIznajmljivanja();

            }

        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblIznajmljivanja = new javax.swing.JTable();
        btnDetalji = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();
        btnZatvori = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtKlijent = new javax.swing.JTextField();
        btnIzmeniIznajmljivanje = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblIznajmljivanja.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblIznajmljivanja);

        btnDetalji.setText("Detalji Iznajmljivanja");
        btnDetalji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetaljiActionPerformed(evt);
            }
        });

        btnObrisi.setText("Obrisi iznajmljivanje");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        btnZatvori.setText("Zatvori");
        btnZatvori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZatvoriActionPerformed(evt);
            }
        });

        jLabel1.setText("Klijent:");

        btnIzmeniIznajmljivanje.setText("izmeni Iznajmljivanje");
        btnIzmeniIznajmljivanje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniIznajmljivanjeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtKlijent))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnDetalji))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnZatvori, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnObrisi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(btnIzmeniIznajmljivanje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtKlijent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(btnIzmeniIznajmljivanje)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDetalji)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnObrisi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnZatvori)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnZatvoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZatvoriActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnZatvoriActionPerformed

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed
        int selectedRow = tblIznajmljivanja.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Morate izabrati iznajmljivanje!", "Greska!", JOptionPane.ERROR_MESSAGE);
            return;
        }

        ModelTabeleIznajmljivanja mt = (ModelTabeleIznajmljivanja) tblIznajmljivanja.getModel();
        Iznajmljivanje iz = mt.getIznajmljivanje(selectedRow);

        int potvrda = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da zelite da obrisete ovo iznajmljivanje?", "Potvrda brisanja", JOptionPane.YES_NO_OPTION);

        if (potvrda != JOptionPane.YES_OPTION) {
            return;
        }

        try {
            Request zahtev = new Request();
            zahtev.setData(iz);
            zahtev.setOperation(Operacije.DELETE_IZNAJMLJIVANJE);

            Komunikacija.getInstance().posaljiZahtev(zahtev);

            Response odgovor = Komunikacija.getInstance().primiOdgovor();
            System.out.println(odgovor.getResult().getClass().getName());
            boolean uspesno = (boolean) odgovor.getResult();
            if (uspesno) {
                JOptionPane.showMessageDialog(this, "Iznajmljivanje je uspesno obrisano!");
                svaIznajmljivanja.removeIf(izn -> izn.getIznajmljivanjeID() == iz.getIznajmljivanjeID());
                filtrirajIznajmljivanja();
            } else {
                JOptionPane.showMessageDialog(this, "Brisanje nije uspelo!", "Greška!", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Greska prilikom brisanja iznajmljivanja!", "Greska!", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnObrisiActionPerformed

    private void btnDetaljiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetaljiActionPerformed
        int selectedRow = tblIznajmljivanja.getSelectedRow();
        
        if(selectedRow == -1){
            JOptionPane.showMessageDialog(this, "Morate da odaberete bar jedno iznajmljivanje!","Greska!",JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        ModelTabeleIznajmljivanja mt = (ModelTabeleIznajmljivanja) tblIznajmljivanja.getModel();
        Iznajmljivanje iz = mt.getIznajmljivanje(selectedRow);
        
        DetaljiIznajmljivanjaForm dif = new DetaljiIznajmljivanjaForm(iz);
        dif.setVisible(true);
    }//GEN-LAST:event_btnDetaljiActionPerformed

    private void btnIzmeniIznajmljivanjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniIznajmljivanjeActionPerformed
        int selectedRow = tblIznajmljivanja.getSelectedRow();
        if(selectedRow == -1){
            JOptionPane.showMessageDialog(this, "Morate da odaberete bar jedno iznajmljivanje!", "Greska!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        ModelTabeleIznajmljivanja mt = (ModelTabeleIznajmljivanja) tblIznajmljivanja.getModel();
        Iznajmljivanje iz = mt.getIznajmljivanje(selectedRow);
        System.out.println("Broj stavki iznajmljivanja je: " + iz.getStavkeIznajmljivanja());
        IzmeniIznajmljivanjeForm izf = new IzmeniIznajmljivanjeForm(this, true, iz);
        izf.setVisible(true);
        
        if(izf.isIzmenjeno()){
            tblIznajmljivanja.repaint();
            mt.fireTableDataChanged();
        }
    }//GEN-LAST:event_btnIzmeniIznajmljivanjeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PretragaIznajmljivanjaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PretragaIznajmljivanjaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PretragaIznajmljivanjaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PretragaIznajmljivanjaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PretragaIznajmljivanjaForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetalji;
    private javax.swing.JButton btnIzmeniIznajmljivanje;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnZatvori;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblIznajmljivanja;
    private javax.swing.JTextField txtKlijent;
    // End of variables declaration//GEN-END:variables

    private void ucitajIznajmljivanja() {
        try {

            Request zahtev = new Request();
            zahtev.setOperation(Operacije.GET_ALL_IZNAJMLJIVANJE);
            Komunikacija.getInstance().posaljiZahtev(zahtev);
            Response odgovor = Komunikacija.getInstance().primiOdgovor();
            svaIznajmljivanja = (ArrayList<Iznajmljivanje>) odgovor.getResult();
            ModelTabeleIznajmljivanja mt = new ModelTabeleIznajmljivanja(svaIznajmljivanja);
            tblIznajmljivanja.setModel(mt);
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Greska prilikom ucitavanja klijenata!", "Greska", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void filtrirajIznajmljivanja() {

        if (svaIznajmljivanja == null) {
            return;
        }
        String text = txtKlijent.getText().toLowerCase().trim();

        if (text.isEmpty()) {
            tblIznajmljivanja.setModel(new ModelTabeleIznajmljivanja(svaIznajmljivanja));
            return;
        }

        ArrayList<Iznajmljivanje> filtrirana = new ArrayList<>();

        for (Iznajmljivanje iznajmljivanje : svaIznajmljivanja) {
            String ime = iznajmljivanje.getKlijent().getIme() != null ? iznajmljivanje.getKlijent().getIme().toLowerCase() : "";
            String prezime = iznajmljivanje.getKlijent().getPrezime() != null ? iznajmljivanje.getKlijent().getPrezime().toLowerCase() : "";
            String punoIme = (ime + " " + prezime).trim();

            if (punoIme.contains(text)) {
                filtrirana.add(iznajmljivanje);
            }
        }
        ModelTabeleIznajmljivanja mt = new ModelTabeleIznajmljivanja(filtrirana);
        tblIznajmljivanja.setModel(mt);
    }
}
