/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import domain.Klijent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import kontroler.Komunikacija;
import modeli.ModelTabeleKlijenti;
import transfer.Request;
import transfer.Response;
import transfer.util.Operacije;

/**
 *
 * @author mihajlodjordjevic
 */
public class PretragaKlijenataForm extends javax.swing.JFrame {

    private ArrayList<Klijent> sviKlijenti;

    /**
     * Creates new form PretragaKlijenataForm
     */
    public PretragaKlijenataForm() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Pretraga klijenata");
        ucitajKlijente();
        txtIme.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                filtrirajKlijente();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                filtrirajKlijente();

            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                filtrirajKlijente();

            }

        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKlijenti = new javax.swing.JTable();
        btnObrisi = new javax.swing.JButton();
        btnZatvori = new javax.swing.JButton();
        txtIme = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblKlijenti.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblKlijenti);

        btnObrisi.setText("Obrisi Klijenta");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        btnZatvori.setText("Zatvori");
        btnZatvori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZatvoriActionPerformed(evt);
            }
        });

        jLabel2.setText("Ime:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(btnObrisi)
                        .addGap(18, 18, 18)
                        .addComponent(btnZatvori, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIme)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnObrisi)
                    .addComponent(btnZatvori))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnZatvoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZatvoriActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnZatvoriActionPerformed

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed
        int selectedRow = tblKlijenti.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Izaberite klijenta za brisanje!", "Greska!", JOptionPane.ERROR_MESSAGE);
            return;
        }

        ModelTabeleKlijenti mt = (ModelTabeleKlijenti) tblKlijenti.getModel();
        Klijent k = mt.getKlijent(selectedRow);

        int potvrda = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da zelite da obrisete klijenta?", "Potvda brisanja", JOptionPane.YES_NO_OPTION);

        if (potvrda != JOptionPane.YES_OPTION) {
            return;
        }

        try {
            Request zahtev = new Request();
            zahtev.setData(k);
            zahtev.setOperation(Operacije.DELETE_KLIJENT);

            Komunikacija.getInstance().posaljiZahtev(zahtev);
            Response odgovor = Komunikacija.getInstance().primiOdgovor();

            boolean uspesno = (boolean) odgovor.getResult();

            if (uspesno) {
                JOptionPane.showMessageDialog(this, "Klijent je uspesno obrisan!");
                sviKlijenti.removeIf(kl -> kl.getKlijentID() == k.getKlijentID());
                filtrirajKlijente();
            } else {
                JOptionPane.showMessageDialog(this, "Greska prilikom brisanja!", "Greska!", JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Greska prilikom brisanja klijenta!", "Greska!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnObrisiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PretragaKlijenataForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PretragaKlijenataForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PretragaKlijenataForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PretragaKlijenataForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PretragaKlijenataForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnZatvori;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblKlijenti;
    private javax.swing.JTextField txtIme;
    // End of variables declaration//GEN-END:variables

    private void ucitajKlijente() {
        try {

            Request zahtev = new Request();
            zahtev.setOperation(Operacije.GET_ALL_KLIJENT);
            Komunikacija.getInstance().posaljiZahtev(zahtev);
            Response odgovor = Komunikacija.getInstance().primiOdgovor();
            sviKlijenti = (ArrayList<Klijent>) odgovor.getResult();
            ModelTabeleKlijenti mt = new ModelTabeleKlijenti(sviKlijenti);
            tblKlijenti.setModel(mt);
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Greska prilikom ucitavanja klijenata!", "Greska", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void filtrirajKlijente() {
        if (sviKlijenti == null) {
            return;
        }

        String tekst = txtIme.getText().toLowerCase();

        if (tekst.isEmpty()) {
            tblKlijenti.setModel(new ModelTabeleKlijenti(sviKlijenti));
            return;
        }

        ArrayList<Klijent> filtrirani = new ArrayList<>();
        for (Klijent klijent : sviKlijenti) {
            String ime = klijent.getIme() != null ? klijent.getIme().toLowerCase() : "";
            String prezime = klijent.getPrezime() != null ? klijent.getPrezime().toLowerCase() : "";
            String punoIme = (ime + " " + prezime).trim();

            if (punoIme.contains(tekst)) {
                filtrirani.add(klijent);
            }
        }
        ModelTabeleKlijenti mt = new ModelTabeleKlijenti(filtrirani);
        tblKlijenti.setModel(mt);
    }
}
